name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Set Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests and generate coverage report
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v > result.log; tail -n 10 result.log

      # Step 5: Upload test results (as artifacts)
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            result.log  # Upload the test result log
            coverage.xml  # You can also upload a coverage report if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # Step 1: Checkout code again
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download the artifact (test results)
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results  # Must match the upload name in the build job

      # Step 3: Display downloaded artifacts (optional)
      - name: Display downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -l
          cat result.log  # Display the test result log

      # You can add deployment steps here as needed, for example:
      # - name: Deploy to server
      #   run: ./deploy.sh
