name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v > result.log || tail -n 20 result.log

      - name: Upload test results
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-results  # The name used to identify the artifact
          path: result.log    # Path to the log file you want to upload

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the deploy job runs after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Download test results
        uses: actions/download-artifact@v4.1.8
        with:
          name: test-results  # Must match the name used in the upload step

      - name: Display downloaded artifact
        run: |
          echo "Displaying downloaded result.log:"
          cat result.log  # Or use the downloaded artifact in any other way you need
